# For more properties (nacos): http://172.18.91.89:8848/nacos

# web service port
server:
  port: 9999

# 将系统日志设置为 debug 级别
logging:
  level:
    root: info

spring:
  application:
    name: LangChainAgent
  profiles:
    active: dev
  data:
    mongodb:
      host: 172.18.91.89
      port: 27017
      database: chat_memory_db
      username: root
      password: lpy123
      authentication-database: admin
  datasource:
    url: jdbc:mysql://172.18.91.89:3306/LangChainAgent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# 开启 SQL 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
