# For more properties (nacos): http://172.19.23.84:8080/

# web service port
server:
  port: 9999

# 将系统日志设置为 debug 级别
logging:
  level:
    root: info

spring:
  application:
    name: LangChainAgent
  profiles:
    active: dev
  data:
    mongodb:
      host: 172.19.23.84
      port: 27017
      database: chat_memory_db
      username: root
      password: lpy123
      authentication-database: admin